# have 2 folders, one with reference and another target. Edit path to both. Set up folder for output files.
# This runs the python script as:    $ python script.py reference_dist target_dist output_file


# make soft links to both filepaths with angle distributions and pass these as arguments $1 and $2. The output folder will be named KL_OUTPUT/$1_$2 with folders for PSI PHI CHI1 and CHI2. 
# Subfolders in the soft links should be as generated by Dihedral.py

# make soft link to 3_KL_run_all_test.py
# make soft link to 4_collate_KL_CHI2.py

# Running Dihedral.py should tell how many psi, phi, chi1 and chi2 angles the system has. Pass these as $3, $4, $5 and $6 respectively. 

# So overall, run this as:   $ 2_script_run_all_KL.sh reference_filepath target_filepath number_psi_angles number_phi_angles number_chi1_angles number_chi2_angles

start=`date +%s`

mkdir KL_OUTPUT
mkdir KL_OUTPUT/$1_$2
mkdir KL_OUTPUT/$1_$2/PSI
mkdir KL_OUTPUT/$1_$2/PHI
mkdir KL_OUTPUT/$1_$2/CHI1
mkdir KL_OUTPUT/$1_$2/CHI2

echo "psi KL calculating ..."
rep=1
while [ $rep -le $3 ];
do
        python ../Scripts/3_KL_run_all.py $1/OUTPUT/PSI/psi_hist_$rep.dat $2/OUTPUT/PSI/psi_hist_$rep.dat KL_OUTPUT/$1_$2/PSI/psi_out_$rep.dat
	rep=$((rep+1))

done


echo "phi KL calculating ..."
rep=1
while [ $rep -le $4 ];
do
        python ../Scripts/3_KL_run_all.py $1/OUTPUT/PHI/phi_hist_$rep.dat $2/OUTPUT/PHI/phi_hist_$rep.dat KL_OUTPUT/$1_$2/PHI/phi_out_$rep.dat
	rep=$((rep+1))

done


echo "chi1 KL calculating ..."

rep=1
while [ $rep -le $5 ];
do
        python ../Scripts/3_KL_run_all.py $1/OUTPUT/CHI1/chi1_hist_$rep.dat $2/OUTPUT/CHI1/chi1_hist_$rep.dat KL_OUTPUT/$1_$2/CHI1/chi1_out_$rep.dat
	rep=$((rep+1))

done

echo "chi2 KL calculating ..."
rep=1
while [ $rep -le $6 ];
do
        python ../Scripts/3_KL_run_all.py $1/OUTPUT/CHI2/chi2_hist_$rep.dat $2/OUTPUT/CHI2/chi2_hist_$rep.dat KL_OUTPUT/$1_$2/CHI2/chi2_out_$rep.dat
	rep=$((rep+1))

done


cd KL_OUTPUT/$1_$2/PSI
python ../../../../Scripts/4_collate_KL_PSI.py $3
cd ../PHI/
python ../../../../Scripts/4_collate_KL_PHI.py $4
cd ../CHI1/
python ../../../../Scripts/4_collate_KL_CHI1.py $5
cd ../CHI2/
python ../../../../Scripts/4_collate_KL_CHI2.py $6

end=`date +%s`

echo "Time in seconds to run KL script:  "
echo $((end-start))

